In [1]:
!pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.12/dist-packages (37.11.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.12/dist-packages (from faker) (2025.2)

In [2]:
import pandas as pd
import numpy as np
from faker import Faker
import random

In [3]:
fake = Faker('id_ID')

In [4]:
total = 100
data_user = []

In [5]:
for _ in range(total):
  user = {
        'username': fake.user_name(),
        'fullName': random.choice([fake.name_male(), fake.name_female()]),
        'email': fake.email(),
        'phoneNumber': fake.numerify(text='08##########'),
        'address': fake.address(),
        'password': 'password123',
        'accountNumber': fake.numerify(text='##########'),
        'isAdmin': False
    }
  data_user.append(user)

In [6]:
df_users = pd.DataFrame(data_user)

In [7]:
display(df_users.head(10))

,username,fullName,email,phoneNumber,address,password,accountNumber,isAdmin
0,ikin33,dr. Jabal Prasasta,utamakayun@example.net,089272850356,"Gang Jend. A. Yani No. 8\nBlitar, MU 93067",password123,8818137742,False
1,hasandongoran,"Darmanto Laksita, S.Ked",bandriani@example.com,086428023162,"Jl. Lembong No. 818\nTomohon, NB 39725",password123,9718828145,False
2,wirdalailasari,Vicky Yolanda,jelitauyainah@example.com,085527949503,"Jalan Suniaraja No. 0\nTarakan, KS 61124",password123,5881355477,False
3,prabususanti,Mursinin Wahyudin,galih63@example.com,083732916495,"Gang S. Parman No. 58\nDepok, KI 45294",password123,1087975933,False
4,siraitrika,Ir. Gading Hartati,wmulyani@example.net,083329787399,"Gg. Monginsidi No. 1\nYogyakarta, Lampung 54547",password123,3773431319,False
5,oagustina,Martaka Pratama,mardhiyahnadia@example.net,087853960123,"Gg. Ciwastra No. 519\nKendari, GO 75833",password123,8984758092,False
6,umansur,Jamil Utama,tirtayasa70@example.com,088051278742,"Jl. Rawamangun No. 7\nTebingtinggi, SU 72112",password123,5992827407,False
7,gunawanrespati,"dr. Patricia Tamba, S.T.",saktimustofa@example.net,088751983259,"Gang Erlangga No. 6\nBitung, KS 83974",password123,0758765872,False
8,talia50,Icha Gunawan,bagusgunawan@example.com,088246080370,"Jalan M.T Haryono No. 6\nPariaman, KB 68774",password123,8400653651,False
9,asmadi20,Ulva Sihombing,sitorusdarman@example.net,088917945673,"Jalan BKR No. 410\nTual, JK 25091",password123,6089473825,False

In [8]:
name = 'therajintitip_user.csv'

df_users.to_csv(name, index=False)